#!/bin/bash
#
# Test for duplicates

function randomness_tester() {

  echo -e "Randomness Tester"

  i="0"
  VAL_ARRAY=()

  DUPLICATE_COUNT="0"
  END=100000

  for (( $i; $i < $END; i++ )); do

    # Get a random string
    STRING=$(random_string)

    # Does it exist in $ARRAY?
    if [[ " ${VAL_ARRAY[@]} " =~ " ${STRING} " ]]; then

      #echo "Dupe"
      DUPLICATE_COUNT=$[$DUPLICATE_COUNT+1]

    fi

    VAL_ARRAY+=("${STRING}")

    i=$[$i+1]

  done

  printf "Duplicates Found: %s\n" "$DUPLICATE_COUNT"

}

random_string() {

  head /dev/urandom | tr -dc '[:print:]' | head -c 64

}

randomness_tester
